/*
 * This file was automatically generated by EvoSuite
 * Tue May 27 00:36:02 GMT 2025
 */

package com.mycompany.solucao1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.mycompany.solucao1.Menu;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Menu_ESTest extends Menu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[] stringArray0 = new String[1];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[] stringArray0 = new String[9];
      SystemInUtil.addInputLine("p");
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.pedeInt("");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[9];
      SystemInUtil.addInputLine("t\" L&]Q\"5K9wq5x_");
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.pedeDouble("UBhLqW}<<W6(");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[1];
      SystemInUtil.addInputLine("dd/MM/yyyy HH:mm:ss");
      Menu menu0 = new Menu(stringArray0);
      String string0 = menu0.pedeString("");
      assertEquals("dd/MM/yyyy HH:mm:ss", string0);
      assertEquals((-1), menu0.getOpcao());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[8];
      Menu menu0 = new Menu(stringArray0);
      SystemInUtil.addInputLine("");
      menu0.pedeString("");
      assertEquals((-1), menu0.getOpcao());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String[] stringArray0 = new String[3];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      menu0.pedeDataHora(";s,XmNJ0V\"");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      menu0.pedeTempo(")bhs}");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[3];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      menu0.pedeData("@^-2JF");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[8];
      SystemInUtil.addInputLine("=&W`[");
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[3];
      Menu menu0 = new Menu(stringArray0);
      int int0 = menu0.getOpcao();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[4];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.pedeString(",3(}5nXYp)AS");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Menu menu0 = null;
      try {
        menu0 = new Menu((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }
}
