/*
 * This file was automatically generated by EvoSuite
 * Fri May 30 18:15:38 GMT 2025
 */

package com.mycompany.solucao1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.mycompany.solucao1.Atividade;
import com.mycompany.solucao1.BicepCurls;
import com.mycompany.solucao1.UtilizadorAmador;
import com.mycompany.solucao1.UtilizadorPraticanteOcasional;
import com.mycompany.solucao1.UtilizadorProfissional;
import java.time.Clock;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.time.chrono.IsoChronology;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.evosuite.runtime.mock.java.time.MockLocalTime;
import org.evosuite.runtime.mock.java.time.MockZonedDateTime;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BicepCurls_ESTest extends BicepCurls_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.from(localDateTime0);
      BicepCurls bicepCurls0 = new BicepCurls(localDateTime0, localTime0, 867, 139, 867);
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador("[PL#%SP`W@]6Ch]]", "\nTipo de Utilizador: Amador\n", "[PL#%SP`W@]6Ch]]", 867, 139, 139, localDate0, 'l');
      utilizadorAmador0.addAtividade(bicepCurls0);
      BicepCurls bicepCurls1 = (BicepCurls)bicepCurls0.geraAtividade(utilizadorAmador0, (-3542.59246));
      assertEquals((-2904), bicepCurls1.getRepeticoes());
      assertEquals(693.6, bicepCurls1.getPeso(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BicepCurls bicepCurls0 = new BicepCurls();
      String string0 = bicepCurls0.toString();
      assertEquals("Atividade\nId: 1\nData e hora: 14/02/2014 20:21:21\nDura\u00E7ao: 00:00\nFrequencia Cardiaca: 0 bpm\nRepeti\u00E7oes: 0\nPeso: 0.0 kilos\nTipo de atividade: Bicep curls\n", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BicepCurls bicepCurls0 = new BicepCurls();
      UtilizadorProfissional utilizadorProfissional0 = new UtilizadorProfissional();
      bicepCurls0.setProximoCodigo((-1));
      Atividade atividade0 = bicepCurls0.geraAtividade(utilizadorProfissional0, (-544.685336129));
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1622);
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("", "", "", 0, 0, 1622, localDate0, '!');
      bicepCurls0.geraAtividade(utilizadorPraticanteOcasional0, 3727.79);
      assertTrue(bicepCurls0.equals((Object)atividade0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      Clock clock0 = MockClock.tickSeconds(zoneOffset0);
      LocalTime localTime0 = MockLocalTime.now(clock0);
      LocalDateTime localDateTime0 = MockLocalDateTime.of(localDate0, localTime0);
      BicepCurls bicepCurls0 = new BicepCurls(localDateTime0, localTime0, 984, 984, 288.361);
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional(")Ay}Q\"\")+", "(uI/.", "\nTipo de atividade: Bicep curls\n", (-1), 984, 984, localDate0, ')');
      double double0 = bicepCurls0.consumoCalorias(utilizadorPraticanteOcasional0);
      assertEquals(1803.251618819445, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Period period0 = Period.ofDays(0);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      LocalTime localTime0 = MockLocalTime.now();
      ZoneId zoneId0 = ZoneId.systemDefault();
      ZonedDateTime zonedDateTime0 = MockZonedDateTime.of(localDate0, localTime0, zoneId0);
      LocalDateTime localDateTime0 = MockLocalDateTime.from(zonedDateTime0);
      BicepCurls bicepCurls0 = new BicepCurls(localDateTime0, localTime0, 3315, 0, 0);
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador("net.bytebuddy.asm.Advice$AssignReturned$Factory", "net.bytebuddy.asm.Advice$AssignReturned$Factory", "g!X3OTDoIm@Y[j{=", 1035, 1035, 1035, localDate0, 'G');
      double double0 = bicepCurls0.consumoCalorias(utilizadorAmador0);
      assertEquals((-4564.795625000003), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BicepCurls bicepCurls0 = new BicepCurls();
      UtilizadorProfissional utilizadorProfissional0 = new UtilizadorProfissional("v", "S5[N[N)p@vaoGm", "v", (-1641), (-1641), (-1641), (LocalDate) null, '<');
      // Undeclared exception!
      try { 
        bicepCurls0.geraAtividade(utilizadorProfissional0, (-1641));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Utilizador", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BicepCurls bicepCurls0 = new BicepCurls();
      bicepCurls0.setDataRealizacao((LocalDateTime) null);
      BicepCurls bicepCurls1 = new BicepCurls(bicepCurls0);
      // Undeclared exception!
      try { 
        bicepCurls1.equals(bicepCurls0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      LocalDateTime localDateTime0 = MockLocalDateTime.now((ZoneId) zoneOffset0);
      BicepCurls bicepCurls0 = new BicepCurls(localDateTime0, (LocalTime) null, (-2420), (-2420), 0.0);
      UtilizadorProfissional utilizadorProfissional0 = new UtilizadorProfissional();
      // Undeclared exception!
      try { 
        bicepCurls0.consumoCalorias(utilizadorProfissional0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.AtivRepeticoes", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BicepCurls bicepCurls0 = null;
      try {
        bicepCurls0 = new BicepCurls((BicepCurls) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      LocalDateTime localDateTime0 = MockLocalDateTime.now((ZoneId) zoneOffset0);
      BicepCurls bicepCurls0 = new BicepCurls(localDateTime0, (LocalTime) null, (-2420), (-2420), 0.0);
      Object object0 = bicepCurls0.clone();
      assertNotSame(object0, bicepCurls0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.now();
      BicepCurls bicepCurls0 = new BicepCurls(localDateTime0, localTime0, 1310, 1310, 1310);
      boolean boolean0 = bicepCurls0.equals(localDateTime0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.now();
      BicepCurls bicepCurls0 = new BicepCurls(localDateTime0, localTime0, (-4), (-4), (-4));
      BicepCurls bicepCurls1 = new BicepCurls(bicepCurls0);
      boolean boolean0 = bicepCurls0.equals(bicepCurls1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.now();
      BicepCurls bicepCurls0 = new BicepCurls(localDateTime0, localTime0, (-4), (-4), (-4));
      boolean boolean0 = bicepCurls0.equals(bicepCurls0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.now();
      BicepCurls bicepCurls0 = new BicepCurls(localDateTime0, localTime0, (-4), (-4), (-4));
      boolean boolean0 = bicepCurls0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      BicepCurls bicepCurls0 = new BicepCurls();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional();
      // Undeclared exception!
      try { 
        bicepCurls0.consumoCalorias(utilizadorPraticanteOcasional0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("com.mycompany.solucao1.AtivRepeticoes", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LocalTime localTime0 = MockLocalTime.of(1, 1, 0, 1452);
      BicepCurls bicepCurls0 = new BicepCurls((LocalDateTime) null, localTime0, 0, 10, 700.0);
      // Undeclared exception!
      try { 
        bicepCurls0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.now();
      BicepCurls bicepCurls0 = new BicepCurls(localDateTime0, localTime0, (-1155), (-1155), (-1155));
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador();
      utilizadorAmador0.addAtividade(bicepCurls0);
      BicepCurls bicepCurls1 = (BicepCurls)bicepCurls0.geraAtividade(utilizadorAmador0, (-1155));
      assertEquals((-536870912), bicepCurls1.getRepeticoes());
      assertEquals((-924.0), bicepCurls1.getPeso(), 0.01);
  }
}
