/*
 * This file was automatically generated by EvoSuite
 * Fri May 30 18:07:56 GMT 2025
 */

package com.mycompany.solucao1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.mycompany.solucao1.Atividade;
import com.mycompany.solucao1.GestorDesportivo;
import com.mycompany.solucao1.PlanoTreino;
import com.mycompany.solucao1.Utilizador;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.StreamCorruptedException;
import java.time.Clock;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.Month;
import java.time.OffsetDateTime;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.evosuite.runtime.mock.java.time.MockLocalTime;
import org.evosuite.runtime.mock.java.time.MockOffsetDateTime;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GestorDesportivo_ESTest extends GestorDesportivo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.now();
      gestorDesportivo0.addUtilizador("=%", "=%", "$,;(", 2147483645, 8, 3189, localDate0, '~', 1);
      int[] intArray0 = new int[3];
      gestorDesportivo0.geraPlanoTreinoUtilizador(1, intArray0, 2147483645, 2, 3325.444156, localDate0);
      assertArrayEquals(new int[] {0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[3];
      gestorDesportivo0.geraPlanoTreinoUtilizador(10, intArray0, 1600, (-1993), (-1.0), (LocalDate) null);
      assertArrayEquals(new int[] {0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.now();
      LocalDate localDate1 = MockLocalDate.now();
      // Undeclared exception!
      try { 
        gestorDesportivo0.metrosAltimetria(9, localDate1, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      // Undeclared exception!
      try { 
        gestorDesportivo0.registaPlanoTreino((-3341), 707);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      Clock clock0 = MockClock.tickMinutes(zoneOffset0);
      LocalDateTime localDateTime0 = MockLocalDateTime.now(clock0);
      LocalTime localTime0 = MockLocalTime.now((ZoneId) zoneOffset0);
      // Undeclared exception!
      try { 
        gestorDesportivo0.addAtivRepsPesoPlano((-3336), 1729, localDateTime0, localTime0, 1729, 8, (-3336), 8);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      ZoneOffset zoneOffset0 = ZoneOffset.ofHoursMinutes(0, 0);
      LocalDateTime localDateTime0 = MockLocalDateTime.now((ZoneId) zoneOffset0);
      LocalTime localTime0 = MockLocalTime.now();
      // Undeclared exception!
      try { 
        gestorDesportivo0.addAtivRepsPesoPlano(5, 5, localDateTime0, localTime0, 0, 0, 0, 11);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalTime localTime0 = MockLocalTime.of(7, 7, 7);
      // Undeclared exception!
      try { 
        gestorDesportivo0.addAtivRepsPesoPlano(7, 7, (LocalDateTime) null, localTime0, (-8), 7, 7, 7);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalTime localTime0 = MockLocalTime.now();
      // Undeclared exception!
      try { 
        gestorDesportivo0.addAtivRepsPesoPlano(0, 0, (LocalDateTime) null, localTime0, 0, 10, 0.0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(3225L);
      // Undeclared exception!
      try { 
        gestorDesportivo0.addAtivRepPlano(1, 1, localDateTime0, localTime0, 1, 1, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.from(localDateTime0);
      // Undeclared exception!
      try { 
        gestorDesportivo0.addAtivDistAltPlano((-2024), 169, localDateTime0, localTime0, 485, 3388.19150985092, 1.0, 169);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(1177);
      // Undeclared exception!
      try { 
        gestorDesportivo0.addAtivDistAltPlano(1177, 1177, (LocalDateTime) null, localTime0, 10, 1177, 1410.4864937545779, 3);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(0);
      // Undeclared exception!
      try { 
        gestorDesportivo0.addAtivDistAltPlano(0, (-1394), (LocalDateTime) null, localTime0, 0, 0, 4, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      Instant instant0 = MockInstant.ofEpochSecond((long) (-1672), (long) (-1672));
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      LocalDateTime localDateTime0 = MockLocalDateTime.ofInstant(instant0, zoneOffset0);
      LocalTime localTime0 = MockLocalTime.now((ZoneId) zoneOffset0);
      // Undeclared exception!
      try { 
        gestorDesportivo0.addAtivDistPlano((-1672), (-1672), localDateTime0, localTime0, (-1672), (-1672), 2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      int int0 = gestorDesportivo0.addAtivRepsPeso(localDateTime0, (LocalTime) null, 1, 1, 1, 8);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(3225L);
      int int0 = gestorDesportivo0.addAtivRepsPeso(localDateTime0, localTime0, 5, 5, 3225L, 1477);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.of(2303, 6, 6, 7, 7, 7, 6);
      LocalTime localTime0 = MockLocalTime.now();
      int int0 = gestorDesportivo0.addAtivRepsPeso(localDateTime0, localTime0, 891, 6, (-2254.7719583), 7);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(3225L);
      int int0 = gestorDesportivo0.addAtivRepsPeso(localDateTime0, localTime0, 5, 5, 3225L, 5);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(3225L);
      int int0 = gestorDesportivo0.addAtivRep(localDateTime0, localTime0, 0, 5, 5);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.ofNanoOfDay(3225L);
      int int0 = gestorDesportivo0.addAtivRep(localDateTime0, localTime0, 5, (-664), 5);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.now();
      int int0 = gestorDesportivo0.addAtivDistAlt(localDateTime0, localTime0, 259, (-2.914460174128226), 259, 259);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalTime localTime0 = MockLocalTime.ofNanoOfDay(0L);
      int int0 = gestorDesportivo0.addAtivDist((LocalDateTime) null, localTime0, 0, 0L, (-962));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int int0 = gestorDesportivo0.addUtilizador("", "Nao existe utilizador com este codigo\n", "=<CW{\"@ol/u:n\"m<X", 247, (-1993), 7, (LocalDate) null, 'H', 3);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      Period period0 = Period.ofYears((-520));
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      int int0 = gestorDesportivo0.addUtilizador("Nao existe utilizador com este codigo\n", "Nao existe plano de treino com este codigo\n", "", 1893, 1515, 806, localDate0, '@', 1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.now();
      Month month0 = Month.FEBRUARY;
      LocalDate localDate1 = MockLocalDate.of(1264, month0, 9);
      // Undeclared exception!
      try { 
        gestorDesportivo0.maisCaloriasGastas(localDate1, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.now();
      // Undeclared exception!
      try { 
        gestorDesportivo0.maisAtividades((LocalDate) null, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      gestorDesportivo0.addUtilizador(":_A*/l,((^r-9", "L", ":_A*/l,((^r-9", (-794), 2064, (-794), localDate0, 'u', 3003);
      gestorDesportivo0.addPlanoTreino(localDate0);
      gestorDesportivo0.registaPlanoTreino(1, 1);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      gestorDesportivo0.addPlanoTreino((LocalDate) null);
      LocalDateTime localDateTime0 = MockLocalDateTime.of(0, 1, 1, 1, 1, 1);
      gestorDesportivo0.addAtivRepsPesoPlano(1, 'L', localDateTime0, (LocalTime) null, 1, 0, 'L', 7);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      OffsetDateTime offsetDateTime0 = MockOffsetDateTime.now();
      LocalDate localDate0 = MockLocalDate.from(offsetDateTime0);
      gestorDesportivo0.addPlanoTreino(localDate0);
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(1);
      LocalDateTime localDateTime0 = MockLocalDateTime.ofEpochSecond(2386L, 1, zoneOffset0);
      LocalTime localTime0 = MockLocalTime.ofNanoOfDay(1142L);
      gestorDesportivo0.addAtivRepPlano(1, 554, localDateTime0, localTime0, 0, (-972), 1031);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalTime localTime0 = MockLocalTime.now();
      LocalDate localDate0 = MockLocalDate.now();
      gestorDesportivo0.addPlanoTreino(localDate0);
      gestorDesportivo0.addAtivDistPlano(1, 1, (LocalDateTime) null, localTime0, 0, 1462L, 1);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.now();
      gestorDesportivo0.addUtilizador("gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", 0, 2706, 2706, localDate0, '-', 2706);
      gestorDesportivo0.atualizaInfo(localDate0);
      Utilizador utilizador0 = gestorDesportivo0.maisCaloriasGastas(localDate0, localDate0);
      assertEquals(2706.0, utilizador0.getPeso(), 0.01);
      assertEquals(2706, utilizador0.getAltura());
      assertEquals('-', utilizador0.getGenero());
      assertEquals(0, utilizador0.getFreqCardiaca());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(7);
      gestorDesportivo0.addUtilizador("gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", 7, 7, 7, localDate0, '-', 7);
      gestorDesportivo0.atualizaInfo(localDate0);
      Utilizador utilizador0 = gestorDesportivo0.maisCaloriasGastas(localDate0, localDate0);
      assertEquals(7.0, utilizador0.getPeso(), 0.01);
      assertEquals('-', utilizador0.getGenero());
      assertEquals(7, utilizador0.getFreqCardiaca());
      assertEquals(7, utilizador0.getAltura());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-17));
      gestorDesportivo0.addUtilizador("gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", (-17), (-17), (-17), localDate0, '-', (-17));
      gestorDesportivo0.atualizaInfo(localDate0);
      Utilizador utilizador0 = gestorDesportivo0.maisCaloriasGastas(localDate0, localDate0);
      assertEquals((-17.0), utilizador0.getPeso(), 0.01);
      assertEquals('-', utilizador0.getGenero());
      assertEquals((-17), utilizador0.getAltura());
      assertEquals((-17), utilizador0.getFreqCardiaca());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(43);
      gestorDesportivo0.addUtilizador("gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", 0, 2706, 2706, localDate0, '-', 2706);
      gestorDesportivo0.atualizaInfo(localDate0);
      Utilizador utilizador0 = gestorDesportivo0.maisAtividades(localDate0, localDate0);
      assertEquals(0, utilizador0.getFreqCardiaca());
      assertEquals('-', utilizador0.getGenero());
      assertEquals(2706.0, utilizador0.getPeso(), 0.01);
      assertEquals(2706, utilizador0.getAltura());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(7);
      gestorDesportivo0.addUtilizador("gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", 7, 7, 7, localDate0, '-', 7);
      gestorDesportivo0.atualizaInfo(localDate0);
      Utilizador utilizador0 = gestorDesportivo0.maisAtividades(localDate0, localDate0);
      assertEquals(7, utilizador0.getAltura());
      assertEquals(7.0, utilizador0.getPeso(), 0.01);
      assertEquals('-', utilizador0.getGenero());
      assertEquals(7, utilizador0.getFreqCardiaca());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-17));
      gestorDesportivo0.addUtilizador("gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", (-17), (-17), (-17), localDate0, '-', (-17));
      gestorDesportivo0.atualizaInfo(localDate0);
      Utilizador utilizador0 = gestorDesportivo0.maisAtividades(localDate0, localDate0);
      assertEquals((-17), utilizador0.getFreqCardiaca());
      assertEquals((-17), utilizador0.getAltura());
      assertEquals((-17.0), utilizador0.getPeso(), 0.01);
      assertEquals('-', utilizador0.getGenero());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[0];
      List<Atividade> list0 = gestorDesportivo0.listaAtividades(intArray0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(7);
      gestorDesportivo0.addUtilizador("gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", 7, 7, 7, localDate0, '-', 7);
      gestorDesportivo0.atualizaInfo(localDate0);
      double double0 = gestorDesportivo0.kmsPercorridos(1, localDate0, localDate0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(482L);
      gestorDesportivo0.addAtivRep((LocalDateTime) null, localTime0, (-623), 247, 70);
      // Undeclared exception!
      try { 
        gestorDesportivo0.showAtividade(1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.now();
      gestorDesportivo0.addUtilizador("n~G>xm?;!f8^_L", "n~G>xm?;!f8^_L", "n~G>xm?;!f8^_L", 2147483645, 2147483645, 2147483645, localDate0, '~', 1);
      Integer integer0 = new Integer(1);
      int[] intArray0 = new int[3];
      gestorDesportivo0.geraPlanoTreinoUtilizador((int) integer0, intArray0, 1, (int) integer0, (-5235.014089), localDate0);
      Class<Object> class0 = Object.class;
      // Undeclared exception!
      try { 
        gestorDesportivo0.recordMaisRepeticoes(class0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.mycompany.solucao1.Corrida cannot be cast to com.mycompany.solucao1.AtivRepeticoes
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(43);
      gestorDesportivo0.addUtilizador("gcNB0%{e.}E2wnrh", (String) null, "gcNB0%{e.}E2wnrh", 0, 2706, 1394, (LocalDate) null, '-', 0);
      gestorDesportivo0.atualizaInfo(localDate0);
      // Undeclared exception!
      try { 
        gestorDesportivo0.mostraInfo();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Utilizador", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      // Undeclared exception!
      try { 
        gestorDesportivo0.listaAtividades((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      // Undeclared exception!
      try { 
        gestorDesportivo0.guardaEstado((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      try { 
        gestorDesportivo0.guardaEstado("");
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[7];
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      // Undeclared exception!
      gestorDesportivo0.geraPlanoTreinoUtilizador(8, intArray0, 8, 983, 983, localDate0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[1];
      ZoneOffset zoneOffset0 = ZoneOffset.ofHours(5);
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      // Undeclared exception!
      try { 
        gestorDesportivo0.geraPlanoTreinoUtilizador(5, intArray0, 5, 5, 0.0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Corrida", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[0];
      Period period0 = Period.ZERO;
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      // Undeclared exception!
      try { 
        gestorDesportivo0.geraPlanoTreinoUtilizador((-1784), intArray0, 1264, 1264, (-1784), localDate0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      Month month0 = Month.AUGUST;
      LocalDateTime localDateTime0 = MockLocalDateTime.of(7, month0, 7, 7, 7, 7, 7);
      int[] intArray0 = new int[2];
      gestorDesportivo0.listaAtividades(intArray0);
      LocalTime localTime0 = MockLocalTime.ofNanoOfDay(1L);
      gestorDesportivo0.addAtivRep(localDateTime0, localTime0, 7, 7, 987);
      // Undeclared exception!
      try { 
        gestorDesportivo0.estadoAtualizado();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      // Undeclared exception!
      try { 
        gestorDesportivo0.carregaEstado((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("Nao existe atividade com este codigo\n");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "0el)/");
      try { 
        gestorDesportivo0.carregaEstado("Nao existe atividade com este codigo\n");
        fail("Expecting exception: StreamCorruptedException");
      
      } catch(StreamCorruptedException e) {
         //
         // invalid stream header: 30656C29
         //
         verifyException("java.io.ObjectInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      gestorDesportivo0.addUtilizador("=<CW{\"@ol/u:n\"m<X", "", "", (-3633), (-3633), (-3633), (LocalDate) null, 'A', 808);
      // Undeclared exception!
      try { 
        gestorDesportivo0.atualizaInfo((LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // date
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      // Undeclared exception!
      try { 
        gestorDesportivo0.atividadesUtilizador(2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      // Undeclared exception!
      try { 
        gestorDesportivo0.atividadesExecutadasUtilizador((-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[9];
      intArray0[0] = 9;
      List<Atividade> list0 = gestorDesportivo0.listaAtividades(intArray0);
      assertEquals(9, list0.size());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[8];
      intArray0[5] = 8;
      List<Atividade> list0 = gestorDesportivo0.listaAtividades(intArray0);
      assertEquals(8, list0.size());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[2];
      intArray0[0] = 7;
      List<Atividade> list0 = gestorDesportivo0.listaAtividades(intArray0);
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[7];
      intArray0[5] = 6;
      List<Atividade> list0 = gestorDesportivo0.listaAtividades(intArray0);
      assertEquals(7, list0.size());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[8];
      intArray0[7] = 5;
      List<Atividade> list0 = gestorDesportivo0.listaAtividades(intArray0);
      assertEquals(8, list0.size());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[3];
      intArray0[1] = 4;
      List<Atividade> list0 = gestorDesportivo0.listaAtividades(intArray0);
      assertEquals(3, list0.size());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[9];
      intArray0[7] = 3;
      List<Atividade> list0 = gestorDesportivo0.listaAtividades(intArray0);
      assertEquals(9, list0.size());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[7];
      intArray0[1] = 2;
      List<Atividade> list0 = gestorDesportivo0.listaAtividades(intArray0);
      assertEquals(7, list0.size());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      int[] intArray0 = new int[8];
      intArray0[4] = 1;
      List<Atividade> list0 = gestorDesportivo0.listaAtividades(intArray0);
      assertEquals(8, list0.size());
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(7);
      gestorDesportivo0.addUtilizador("gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", 7, 7, 7, localDate0, '-', 7);
      gestorDesportivo0.atualizaInfo(localDate0);
      String string0 = gestorDesportivo0.mostraInfo();
      assertEquals("Utilizador\nCodigo de Utilizador: 1\nNome: gcNB0%{e.}E2wnrh\nMorada: gcNB0%{e.}E2wnrh\nEmail: gcNB0%{e.}E2wnrh\nFrequencia Cardiaca: 7 bpm\nPeso: 7.0 kilos\nAltura: 7 centimetros\nData de nascimento 08/01/1970\nIdade: 44 anos\nGenero: -\nAtividades: \n\nPlanos de treino: \n\nTipo de Utilizador: Praticante Ocasional\n", string0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      String string0 = gestorDesportivo0.mostraInfo();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.now();
      gestorDesportivo0.addUtilizador("n~G>xm?;!f8^_L", "n~G>xm?;!f8^_L", "n~G>xm?;!f8^_L", 2147483645, 2147483645, 2147483645, localDate0, '~', 1);
      Integer integer0 = new Integer(1);
      int[] intArray0 = new int[3];
      gestorDesportivo0.geraPlanoTreinoUtilizador((int) integer0, intArray0, 1, (int) integer0, (-5235.014089), localDate0);
      assertArrayEquals(new int[] {0, 0, 0}, intArray0);
      
      String string0 = gestorDesportivo0.atividadesUtilizador(1);
      assertEquals("Atividade\nId: 1\nData e hora: 14/02/2014 20:21:21\nDura\u00E7ao: 00:00\nFrequencia Cardiaca: 0 bpm\nDistancia: 0.0 metros\nTipo de atividade: Corrida\n", string0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-17));
      gestorDesportivo0.addUtilizador("gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", (-17), (-17), (-17), localDate0, '-', (-17));
      gestorDesportivo0.atualizaInfo(localDate0);
      String string0 = gestorDesportivo0.atividadesExecutadasUtilizador(1);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      Instant instant0 = MockInstant.ofEpochSecond((long) 1);
      ZoneOffset zoneOffset0 = ZoneOffset.ofHours(1);
      LocalDateTime localDateTime0 = MockLocalDateTime.ofInstant(instant0, zoneOffset0);
      // Undeclared exception!
      try { 
        gestorDesportivo0.addAtivRepsPesoPlano('~', 2147483645, localDateTime0, (LocalTime) null, '~', 2147483645, 1, 8);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(3225L);
      // Undeclared exception!
      try { 
        gestorDesportivo0.addAtivRepPlano(5, 3016, localDateTime0, localTime0, 0, 795, 5);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.of(7, 7, 7, 7, 7, 7, 7);
      LocalTime localTime0 = MockLocalTime.of(7, 7, 7);
      // Undeclared exception!
      try { 
        gestorDesportivo0.addAtivDistPlano(20, 7, localDateTime0, localTime0, 644, 7, 7);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.of(2303, 6, 6, 8, 8, 8, 6);
      LocalTime localTime0 = MockLocalTime.now();
      int int0 = gestorDesportivo0.addAtivRepsPeso(localDateTime0, localTime0, 8, 6, (-2254.7719583), 8);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(3225L);
      int int0 = gestorDesportivo0.addAtivDistAlt(localDateTime0, localTime0, 5, 0.31742826826426995, 5, 3);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      ZoneOffset zoneOffset0 = ZoneOffset.ofHours(6);
      LocalDateTime localDateTime0 = MockLocalDateTime.now((ZoneId) zoneOffset0);
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(1);
      int int0 = gestorDesportivo0.addAtivDistAlt(localDateTime0, localTime0, (-3045), 0.2, 0.0, (-439));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      boolean boolean0 = gestorDesportivo0.existePlano((-17));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds((-3410));
      LocalDateTime localDateTime0 = MockLocalDateTime.ofEpochSecond((-213L), 6, zoneOffset0);
      LocalTime localTime0 = MockLocalTime.from(localDateTime0);
      gestorDesportivo0.addAtivDist(localDateTime0, localTime0, (-429), 6, 1);
      boolean boolean0 = gestorDesportivo0.existeAtividade(1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      boolean boolean0 = gestorDesportivo0.existeAtividade(8);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.now();
      gestorDesportivo0.addUtilizador("", "", "", 0, (-664), 8, localDate0, 'u', 8);
      boolean boolean0 = gestorDesportivo0.existeUtilizador(1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      boolean boolean0 = gestorDesportivo0.existeUtilizador(172);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      gestorDesportivo0.addPlanoTreino((LocalDate) null);
      String string0 = gestorDesportivo0.showPlanoTreino(1);
      assertEquals("Plano de Treino\nCodigo de Plano de Treino: 1\nData de realiza\u00E7ao: null\nAtividades e suas itera\u00E7oes: \n", string0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      String string0 = gestorDesportivo0.showPlanoTreino(7);
      assertEquals("Nao existe plano de treino com este codigo\n", string0);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.of(7, 7, 7, 7, 7, 7, 7);
      LocalTime localTime0 = MockLocalTime.of(7, 7, 7);
      gestorDesportivo0.addAtivRepsPeso(localDateTime0, localTime0, 7, 7, 7, 7);
      String string0 = gestorDesportivo0.showAtividade(2);
      assertEquals("Atividade\nId: 2\nData e hora: 07/07/0007 07:07:07\nDura\u00E7ao: 07:07:07\nFrequencia Cardiaca: 7 bpm\nRepeti\u00E7oes: 7\nPeso: 7.0 kilos\nTipo de atividade: Bicep curls\n", string0);
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      String string0 = gestorDesportivo0.showAtividade(2);
      assertEquals("Nao existe atividade com este codigo\n", string0);
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      gestorDesportivo0.addUtilizador("=<CW{\"@ol/u:n\"m<X", "", "", (-3633), (-3633), (-3633), (LocalDate) null, 'A', 808);
      // Undeclared exception!
      try { 
        gestorDesportivo0.showUtilizador(1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Utilizador", e);
      }
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      String string0 = gestorDesportivo0.showUtilizador(7);
      assertEquals("Nao existe utilizador com este codigo\n", string0);
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.now();
      gestorDesportivo0.addUtilizador("n~G>xm?;!f8^_L", "n~G>xm?;!f8^_L", "n~G>xm?;!f8^_L", 2147483645, 2147483645, 2147483645, localDate0, '~', 1);
      String string0 = gestorDesportivo0.atividadesUtilizador(1);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      String string0 = gestorDesportivo0.atividadeMaisRealizada();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(55);
      PlanoTreino planoTreino0 = gestorDesportivo0.planoTreinoMaisCalorias(localDate0);
      assertNull(planoTreino0);
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.now();
      gestorDesportivo0.addUtilizador("gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", "gcNB0%{e.}E2wnrh", 0, 2706, 2706, localDate0, '-', 2706);
      gestorDesportivo0.atualizaInfo(localDate0);
      // Undeclared exception!
      try { 
        gestorDesportivo0.planoTreinoMaisCalorias(localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Utilizador", e);
      }
  }

  @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      gestorDesportivo0.addPlanoTreino((LocalDate) null);
      gestorDesportivo0.estadoAtualizado();
  }

  @Test(timeout = 4000)
  public void test87()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      LocalTime localTime0 = MockLocalTime.ofSecondOfDay(3225L);
      gestorDesportivo0.addAtivRep(localDateTime0, localTime0, (-30), (-664), 0);
      gestorDesportivo0.estadoAtualizado();
  }

  @Test(timeout = 4000)
  public void test88()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      gestorDesportivo0.addUtilizador("Nao existe utilizador com este codigo\n", "Nao existe utilizador com este codigo\n", "Nao existe utilizador com este codigo\n", 0, 0, 0, (LocalDate) null, 'L', 'L');
      gestorDesportivo0.estadoAtualizado();
  }

  @Test(timeout = 4000)
  public void test89()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.now();
      gestorDesportivo0.addPlanoTreino(localDate0);
      boolean boolean0 = gestorDesportivo0.existePlano(1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test90()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      // Undeclared exception!
      try { 
        gestorDesportivo0.registaAtividade('u', 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test91()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0);
      // Undeclared exception!
      try { 
        gestorDesportivo0.kmsPercorridos(0, (LocalDate) null, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.GestorDesportivo", e);
      }
  }

  @Test(timeout = 4000)
  public void test92()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      try { 
        gestorDesportivo0.carregaEstado("K vQ$c;xCe1NUS");
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test93()  throws Throwable  {
      GestorDesportivo gestorDesportivo0 = new GestorDesportivo();
      try { 
        gestorDesportivo0.guardaEstado("com.mycompany.solucao1.GestorDesportivo");
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Error in writing to file
         //
         verifyException("org.evosuite.runtime.mock.java.io.NativeMockedIO", e);
      }
  }
}
