/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 04 19:39:15 GMT 2025
 */

package com.mycompany.solucao1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.mycompany.solucao1.Menu;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Menu_ESTest extends Menu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[] stringArray0 = new String[2];
      SystemInUtil.addInputLine("M)TMDNl[%");
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.pedeInt("");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      SystemInUtil.addInputLine("pf WKf6");
      // Undeclared exception!
      try { 
        menu0.pedeDouble("{f0!?)ghbV\"4p)/");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[3];
      SystemInUtil.addInputLine("/");
      Menu menu0 = new Menu(stringArray0);
      menu0.pedeString("/");
      assertEquals((-1), menu0.getOpcao());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[8];
      SystemInUtil.addInputLine("");
      Menu menu0 = new Menu(stringArray0);
      String string0 = menu0.pedeString("rO0");
      assertEquals((-1), menu0.getOpcao());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SystemInUtil.addInputLine("9");
      String[] stringArray0 = new String[1];
      Menu menu0 = new Menu(stringArray0);
      int int0 = menu0.pedeInt("9");
      assertEquals(9, int0);
      assertEquals((-1), menu0.getOpcao());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SystemInUtil.addInputLine("9");
      String[] stringArray0 = new String[1];
      Menu menu0 = new Menu(stringArray0);
      double double0 = menu0.pedeDouble("3#3{wB");
      assertEquals(9.0, double0, 0.01);
      assertEquals((-1), menu0.getOpcao());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      String[] stringArray0 = new String[10];
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      
      menu0.runMenu();
      int int0 = menu0.getOpcao();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[1];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[3];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.pedeString("/");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[3];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      menu0.pedeDataHora("|/#^");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[2];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      menu0.pedeTempo("0");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String[] stringArray0 = new String[10];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      menu0.pedeData("Inserir um n\u00FAmero");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      String[] stringArray0 = new String[2];
      Menu menu0 = new Menu(stringArray0);
      double double0 = menu0.pedeDouble("dd/MM/yyyy HH:mm:ss");
      assertEquals(0.0, double0, 0.01);
      assertEquals((-1), menu0.getOpcao());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      String[] stringArray0 = new String[2];
      Menu menu0 = new Menu(stringArray0);
      int int0 = menu0.pedeInt("-------------");
      assertEquals((-1), menu0.getOpcao());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      String[] stringArray0 = new String[2];
      Menu menu0 = new Menu(stringArray0);
      assertEquals((-1), menu0.getOpcao());
      
      menu0.runMenu();
      assertEquals(0, menu0.getOpcao());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String[] stringArray0 = new String[4];
      SystemInUtil.addInputLine("|/#^");
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String[] stringArray0 = new String[2];
      Menu menu0 = new Menu(stringArray0);
      int int0 = menu0.getOpcao();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SystemInUtil.addInputLine("9");
      String[] stringArray0 = new String[9];
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Menu menu0 = null;
      try {
        menu0 = new Menu((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }
}
