/*
 * This file was automatically generated by EvoSuite
 * Fri May 30 18:24:03 GMT 2025
 */

package com.mycompany.solucao1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.mycompany.solucao1.Corrida;
import com.mycompany.solucao1.Utilizador;
import com.mycompany.solucao1.UtilizadorAmador;
import com.mycompany.solucao1.UtilizadorPraticanteOcasional;
import com.mycompany.solucao1.UtilizadorProfissional;
import java.time.Clock;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneOffset;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.evosuite.runtime.mock.java.time.MockLocalTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Corrida_ESTest extends Corrida_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Corrida corrida0 = new Corrida();
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1));
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional("", "j$M0KO~OL4", "j$M0KO~OL4", (-1), (-1), (-1), localDate0, ',');
      Corrida corrida1 = (Corrida)corrida0.geraAtividade(utilizadorPraticanteOcasional0, (-1));
      assertEquals(0, corrida1.getFreqCardiaca());
      assertEquals((-90.2), corrida1.getDistancia(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDateTime localDateTime0 = MockLocalDateTime.now(clock0);
      LocalTime localTime0 = MockLocalTime.of(0, 0, 1);
      Corrida corrida0 = new Corrida(localDateTime0, localTime0, 5486, 5486);
      String string0 = corrida0.toString();
      assertEquals("Atividade\nId: 1\nData e hora: 14/02/2014 20:21:21\nDura\u00E7ao: 00:00:01\nFrequencia Cardiaca: 5486 bpm\nDistancia: 5486.0 metros\nTipo de atividade: Corrida\n", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDateTime localDateTime0 = MockLocalDateTime.now(clock0);
      LocalTime localTime0 = MockLocalTime.of(0, 0, 1);
      Corrida corrida0 = new Corrida(localDateTime0, localTime0, 5486, 5486);
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador();
      corrida0.setProximoCodigo((-1));
      corrida0.geraAtividade(utilizadorAmador0, 0);
      Corrida corrida1 = (Corrida)corrida0.geraAtividade(utilizadorAmador0, 5.0E-4);
      assertEquals(0, corrida1.getFreqCardiaca());
      assertEquals(4.724464023400001E9, corrida1.getDistancia(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDateTime localDateTime0 = MockLocalDateTime.now(clock0);
      LocalTime localTime0 = MockLocalTime.of(0, 0, 1);
      Corrida corrida0 = new Corrida(localDateTime0, localTime0, 5486, 5486);
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador();
      double double0 = corrida0.consumoCalorias(utilizadorAmador0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LocalTime localTime0 = MockLocalTime.now();
      Corrida corrida0 = new Corrida((LocalDateTime) null, localTime0, 1, 1);
      Clock clock0 = MockClock.systemUTC();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      UtilizadorProfissional utilizadorProfissional0 = new UtilizadorProfissional("e>o7DV;q", "e>o7DV;q", "e>o7DV;q", 1, 1, 1, localDate0, 'h');
      double double0 = corrida0.consumoCalorias(utilizadorProfissional0);
      assertEquals(67.92096157407407, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(177);
      Clock clock0 = MockClock.tickSeconds(zoneOffset0);
      LocalTime localTime0 = MockLocalTime.now(clock0);
      Corrida corrida0 = new Corrida((LocalDateTime) null, localTime0, 1864, 177);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(177);
      UtilizadorProfissional utilizadorProfissional0 = new UtilizadorProfissional("", "", "", 177, 167, (-2453), localDate0, 'b');
      double double0 = corrida0.consumoCalorias(utilizadorProfissional0);
      assertEquals((-19795.810023611106), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.UTC;
      LocalDateTime localDateTime0 = MockLocalDateTime.ofEpochSecond(533L, 0, zoneOffset0);
      LocalTime localTime0 = MockLocalTime.of(0, 0, 0);
      Corrida corrida0 = new Corrida(localDateTime0, localTime0, 0, 0);
      UtilizadorAmador utilizadorAmador0 = new UtilizadorAmador("\nTipo de atividade: Corrida\n", "\nTipo de atividade: Corrida\n", "ot\"UHI3J+\"", 0, 0, 0, (LocalDate) null, 'm');
      // Undeclared exception!
      try { 
        corrida0.geraAtividade(utilizadorAmador0, 0.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Utilizador", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Corrida corrida0 = new Corrida();
      // Undeclared exception!
      try { 
        corrida0.consumoCalorias((Utilizador) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Corrida", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Corrida corrida0 = null;
      try {
        corrida0 = new Corrida((Corrida) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Corrida corrida0 = new Corrida();
      Corrida corrida1 = new Corrida(corrida0);
      assertEquals(0.0, corrida1.getDistancia(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalTime localTime0 = MockLocalTime.now(clock0);
      Corrida corrida0 = new Corrida((LocalDateTime) null, localTime0, (-2696), (-2696));
      Object object0 = corrida0.clone();
      // Undeclared exception!
      try { 
        corrida0.equals(object0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Corrida corrida0 = new Corrida();
      boolean boolean0 = corrida0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Clock clock0 = MockClock.systemDefaultZone();
      LocalTime localTime0 = MockLocalTime.now(clock0);
      Corrida corrida0 = new Corrida((LocalDateTime) null, localTime0, (-2696), (-2696));
      boolean boolean0 = corrida0.equals(corrida0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Corrida corrida0 = new Corrida();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional();
      boolean boolean0 = corrida0.equals(utilizadorPraticanteOcasional0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Corrida corrida0 = new Corrida();
      UtilizadorPraticanteOcasional utilizadorPraticanteOcasional0 = new UtilizadorPraticanteOcasional();
      // Undeclared exception!
      try { 
        corrida0.consumoCalorias(utilizadorPraticanteOcasional0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("com.mycompany.solucao1.Atividade", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Corrida corrida0 = new Corrida((LocalDateTime) null, (LocalTime) null, 70, 0.0);
      // Undeclared exception!
      try { 
        corrida0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.mycompany.solucao1.Atividade", e);
      }
  }
}
